package com.pointlion.sys.mvc.common.model;

import com.pointlion.sys.mvc.common.model.base.BaseSysUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserInfo extends BaseSysUserInfo<SysUserInfo> {
	public static final SysUserInfo dao = new SysUserInfo();
	
}
